from app.reports.md_gen import generate_markdown


def base_args():
    return {
        "title": "Weekly Report",
        "week_start": "2026-01-01",
        "week_end": "2026-01-07",
        "executive_summary": "This is the executive summary.",
        "source_count": 5,
        "insights": [],
        "action_items": [],
        "quotes": [],
        "themes": [],
        "opportunities": [],
        "contradictions": [],
    }


def test_generate_markdown_minimal_args():
    result = generate_markdown(**base_args())

    assert "# Weekly Report" in result
    assert "**Week:** 2026-01-01 to 2026-01-07" in result
    assert "**Sources processed:** 5" in result
    assert "## Executive Summary" in result
    assert "This is the executive summary." in result
    assert "Generated by SignalForge" in result


def test_generate_markdown_all_sections_populated():
    args = base_args()
    args.update(
        {
            "insights": ["Insight one", "Insight two"],
            "action_items": ["Do something"],
            "quotes": ["Important quote"],
            "themes": ["AI", "Automation"],
            "opportunities": ["New market"],
            "contradictions": ["Unexpected result"],
            "core_ideas": ["Core idea"],
            "why_it_matters": ["It matters because of impact"],
            "open_questions": ["What happens next?"],
            "sources": [
                {
                    "title": "Example Source",
                    "url": "https://example.com",
                    "source_type": "Article",
                }
            ],
            "report_sections": {
                "key_developments": ["Development"],
                "cross_source_connections": ["Connection"],
                "recommended_actions": ["Recommendation"],
                "signals_to_monitor": ["Signal"],
            },
        }
    )

    result = generate_markdown(**args)

    assert "## Core Ideas" in result
    assert "## Recurring Themes" in result
    assert "## Key Insights" in result
    assert "## Contrarian / Surprising Points" in result
    assert "## Actionable Takeaways" in result
    assert "## Key Quotes" in result
    assert "## Opportunities" in result
    assert "## Why This Matters" in result
    assert "## Open Questions" in result
    assert "## Sources" in result


def test_generate_markdown_empty_optional_fields_have_no_headers():
    args = base_args()
    args.update(
        {
            "core_ideas": [],
            "why_it_matters": [],
            "open_questions": [],
            "sources": [],
            "report_sections": {},
        }
    )

    result = generate_markdown(**args)

    assert "## Core Ideas" not in result
    assert "## Why This Matters" not in result
    assert "## Open Questions" not in result
    assert "## Sources" not in result
    assert "## Key Developments" not in result


def test_generate_markdown_single_items():
    args = base_args()
    args.update(
        {
            "insights": ["Single insight"],
            "themes": ["Single theme"],
            "action_items": ["Single action"],
        }
    )

    result = generate_markdown(**args)

    assert "1. Single insight" in result
    assert "- Single theme" in result
    assert "- [ ] Single action" in result


def test_generate_markdown_multiple_items():
    args = base_args()
    args.update(
        {
            "insights": ["First", "Second", "Third"],
            "themes": ["Theme A", "Theme B"],
            "quotes": ["Quote A", "Quote B"],
        }
    )

    result = generate_markdown(**args)

    assert "1. First" in result
    assert "2. Second" in result
    assert "3. Third" in result
    assert "- Theme A" in result
    assert "- Theme B" in result
    assert "> Quote A" in result
    assert "> Quote B" in result


def test_generate_markdown_opportunity_dictionary_format():
    args = base_args()
    args.update(
        {
            "opportunities": [
                {
                    "opportunity": "Expand product",
                    "why": "High customer demand",
                }
            ]
        }
    )

    result = generate_markdown(**args)

    assert "## Opportunities" in result
    assert "- **Expand product**" in result
    assert "  - *Why:* High customer demand" in result


def test_generate_markdown_long_strings():
    long_text = "A" * 5000

    args = base_args()
    args.update(
        {
            "executive_summary": long_text,
            "insights": [long_text],
            "quotes": [long_text],
        }
    )

    result = generate_markdown(**args)

    assert long_text in result
    assert "## Key Insights" in result
    assert "## Key Quotes" in result


def test_generate_markdown_report_sections():
    args = base_args()
    args.update(
        {
            "report_sections": {
                "key_developments": ["New feature released"],
                "cross_source_connections": ["Common pattern"],
                "recommended_actions": ["Review data"],
                "signals_to_monitor": ["Market changes"],
            }
        }
    )

    result = generate_markdown(**args)

    assert "## Key Developments" in result
    assert "- New feature released" in result
    assert "## Cross-Source Connections" in result
    assert "- Common pattern" in result
    assert "## Recommended Actions" in result
    assert "- Review data" in result
    assert "## Signals to Monitor" in result
    assert "- Market changes" in result


def test_generate_markdown_source_without_url():
    args = base_args()
    args.update(
        {
            "sources": [
                {
                    "title": "Source Title",
                    "source_type": "Report",
                }
            ]
        }
    )

    result = generate_markdown(**args)

    assert "## Sources" in result
    assert "- [Source Title](#) (Report)" in result

def test_generate_markdown_core_sections():
    args = base_args()
    args.update(
        {
            "title": "Weekly Intel",
            "week_start": "2026-07-14",
            "week_end": "2026-07-20",
            "executive_summary": "Things happened.",
            "source_count": 3,
            "insights": ["Insight A", "Insight B"],
            "action_items": ["Do X"],
            "quotes": ["Ship it"],
            "themes": ["AI"],
            "opportunities": [
                {
                    "opportunity": "Grow",
                    "why": "Demand",
                }
            ],
            "contradictions": ["Surprise"],
            "core_ideas": ["Core 1"],
            "why_it_matters": ["Matters"],
            "open_questions": ["What next?"],
            "sources": [
                {
                    "title": "Blog",
                    "url": "https://example.com",
                    "source_type": "web",
                }
            ],
        }
    )

    md = generate_markdown(**args)

    assert md.startswith("# Weekly Intel")
    assert "Executive Summary" in md
    assert "Insight A" in md
    assert "- [ ] Do X" in md
    assert "> Ship it" in md
    assert "example.com" in md
    assert "Generated by SignalForge" in md


def test_generate_markdown_minimal():
    args = base_args()
    args.update(
        {
            "title": "T",
            "week_start": "a",
            "week_end": "b",
            "executive_summary": "sum",
            "source_count": 0,
        }
    )

    md = generate_markdown(**args)

    assert "# T" in md
    assert "sum" in md
