from app.reports.md_gen import generate_markdown


def base_args():
    return {
        "title": "Weekly Report",
        "week_start": "2026-01-01",
        "week_end": "2026-01-07",
        "executive_summary": "This is the executive summary.",
        "source_count": 5,
        "insights": [],
        "action_items": [],
        "quotes": [],
        "themes": [],
        "opportunities": [],
        "contradictions": [],
    }


def test_generate_markdown_minimal_args():
    result = generate_markdown(**base_args())

    assert "# Weekly Report" in result
    assert "**Week:** 2026-01-01 to 2026-01-07" in result
    assert "**Sources processed:** 5" in result
    assert "## Executive Summary" in result
    assert "This is the executive summary." in result
    assert "Generated by SignalForge" in result


def test_generate_markdown_all_sections_populated():
    args = base_args()

    args.update(
        {
            "insights": ["Insight one", "Insight two"],
            "action_items": ["Do something"],
            "quotes": ["Important quote"],
            "themes": ["AI", "Automation"],
            "opportunities": ["New market"],
            "contradictions": ["Unexpected result"],
            "core_ideas": ["Core idea"],
            "why_it_matters": ["It matters because of impact"],
            "open_questions": ["What happens next?"],
            "sources": [
                {
                    "title": "Example Source",
                    "url": "https://example.com",
                    "source_type": "Article",
                }
            ],
            "report_sections": {
                "key_developments": ["Development"],
                "cross_source_connections": ["Connection"],
                "recommended_actions": ["Recommendation"],
                "signals_to_monitor": ["Signal"],
            },
        }
    )

    result = generate_markdown(**args)

    assert "## Core Ideas" in result
    assert "## Recurring Themes" in result
    assert "## Key Insights" in result
    assert "## Contrarian / Surprising Points" in result
    assert "## Actionable Takeaways" in result
    assert "## Key Quotes" in result
    assert "## Opportunities" in result
    assert "## Why This Matters" in result
    assert "## Open Questions" in result
    assert "## Sources" in result


def test_generate_markdown_empty_optional_fields_have_no_headers():
    result = generate_markdown(
        **base_args(),
        core_ideas=[],
        why_it_matters=[],
        open_questions=[],
        sources=[],
        report_sections={},
    )

    assert "## Core Ideas" not in result
    assert "## Why This Matters" not in result
    assert "## Open Questions" not in result
    assert "## Sources" not in result
    assert "## Key Developments" not in result


def test_generate_markdown_single_items():
    result = generate_markdown(
        **base_args(),
        insights=["Single insight"],
        themes=["Single theme"],
        action_items=["Single action"],
    )

    assert "1. Single insight" in result
    assert "- Single theme" in result
    assert "- [ ] Single action" in result


def test_generate_markdown_multiple_items():
    result = generate_markdown(
        **base_args(),
        insights=["First", "Second", "Third"],
        themes=["Theme A", "Theme B"],
        quotes=["Quote A", "Quote B"],
    )

    assert "1. First" in result
    assert "2. Second" in result
    assert "3. Third" in result
    assert "- Theme A" in result
    assert "- Theme B" in result
    assert "> Quote A" in result
    assert "> Quote B" in result


def test_generate_markdown_opportunity_dictionary_format():
    result = generate_markdown(
        **base_args(),
        opportunities=[
            {
                "opportunity": "Expand product",
                "why": "High customer demand",
            }
        ],
    )

    assert "## Opportunities" in result
    assert "- **Expand product**" in result
    assert "  - *Why:* High customer demand" in result


def test_generate_markdown_long_strings():
    long_text = "A" * 5000

    result = generate_markdown(
        **base_args(),
        executive_summary=long_text,
        insights=[long_text],
        quotes=[long_text],
    )

    assert long_text in result
    assert "## Key Insights" in result
    assert "## Key Quotes" in result


def test_generate_markdown_report_sections():
    result = generate_markdown(
        **base_args(),
        report_sections={
            "key_developments": ["New feature released"],
            "cross_source_connections": ["Common pattern"],
            "recommended_actions": ["Review data"],
            "signals_to_monitor": ["Market changes"],
        },
    )

    assert "## Key Developments" in result
    assert "- New feature released" in result
    assert "## Cross-Source Connections" in result
    assert "- Common pattern" in result
    assert "## Recommended Actions" in result
    assert "- Review data" in result
    assert "## Signals to Monitor" in result
    assert "- Market changes" in result


def test_generate_markdown_source_without_url():
    result = generate_markdown(
        **base_args(),
        sources=[
            {
                "title": "Source Title",
                "source_type": "Report",
            }
        ],
    )

    assert "## Sources" in result
    assert "- [Source Title](#) (Report)" in result

