from app.reports.md_gen import generate_markdown


def test_generate_markdown_core_sections():
    md = generate_markdown(
        title="Weekly Intel",
        week_start="2026-07-14",
        week_end="2026-07-20",
        executive_summary="Things happened.",
        source_count=3,
        insights=["Insight A", "Insight B"],
        action_items=["Do X"],
        quotes=["Ship it"],
        themes=["AI"],
        opportunities=[{"opportunity": "Grow", "why": "Demand"}],
        contradictions=["Surprise"],
        core_ideas=["Core 1"],
        why_it_matters=["Matters"],
        open_questions=["What next?"],
        sources=[{"title": "Blog", "url": "https://example.com", "source_type": "web"}],
    )
    assert md.startswith("# Weekly Intel")
    assert "Executive Summary" in md
    assert "Insight A" in md
    assert "- [ ] Do X" in md
    assert "> Ship it" in md
    assert "example.com" in md
    assert "Generated by SignalForge" in md


def test_generate_markdown_minimal():
    md = generate_markdown(
        title="T",
        week_start="a",
        week_end="b",
        executive_summary="sum",
        source_count=0,
        insights=[],
        action_items=[],
        quotes=[],
        themes=[],
        opportunities=[],
        contradictions=[],
    )
    assert "# T" in md
    assert "sum" in md
