from datetime import datetime


def generate_markdown(title: str, week_start: str, week_end: str,
                      executive_summary: str, source_count: int,
                      insights: list, action_items: list, quotes: list,
                      themes: list, opportunities: list, contradictions: list,
                      sources: list | None = None) -> str:
    lines = []
    lines.append(f"# {title}")
    lines.append("")
    lines.append(f"**Week:** {week_start} to {week_end}")
    lines.append(f"**Sources processed:** {source_count}")
    lines.append(f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    lines.append("")
    lines.append("---")
    lines.append("")

    lines.append("## Executive Summary")
    lines.append("")
    lines.append(executive_summary)
    lines.append("")

    if themes:
        lines.append("## Recurring Themes")
        lines.append("")
        for t in themes:
            lines.append(f"- {t}")
        lines.append("")

    if insights:
        lines.append("## Key Insights")
        lines.append("")
        for i, insight in enumerate(insights, 1):
            lines.append(f"{i}. {insight}")
        lines.append("")

    if action_items:
        lines.append("## Action Items")
        lines.append("")
        for a in action_items:
            lines.append(f"- [ ] {a}")
        lines.append("")

    if quotes:
        lines.append("## Important Quotes")
        lines.append("")
        for q in quotes:
            lines.append(f"> {q}")
        lines.append("")

    if opportunities:
        lines.append("## Opportunities")
        lines.append("")
        for o in opportunities:
            lines.append(f"- **{o.get('opportunity', o)}**")
            if isinstance(o, dict) and o.get("why"):
                lines.append(f"  - *Why:* {o['why']}")
        lines.append("")

    if contradictions:
        lines.append("## Contradictions & Tensions")
        lines.append("")
        for c in contradictions:
            lines.append(f"- {c}")
        lines.append("")

    if sources:
        lines.append("## Sources")
        lines.append("")
        for s in sources:
            if s:
                lines.append(f"- [{s['title']}]({s.get('url', '#')}) ({s['source_type']})")
        lines.append("")

    lines.append("---")
    lines.append(f"*Generated by SignalForge*")

    return "\n".join(lines)
