from datetime import datetime


def generate_markdown(title: str, week_start: str, week_end: str,
                      executive_summary: str, source_count: int,
                      insights: list, action_items: list, quotes: list,
                      themes: list, opportunities: list, contradictions: list,
                      core_ideas: list | None = None,
                      why_it_matters: list | None = None,
                      open_questions: list | None = None,
                      sources: list | None = None,
                      report_sections: dict | None = None) -> str:
    lines = []
    lines.append(f"# {title}")
    lines.append("")
    lines.append(f"**Week:** {week_start} to {week_end}")
    lines.append(f"**Sources processed:** {source_count}")
    lines.append(f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    lines.append("")
    lines.append("---")
    lines.append("")

    lines.append("## Executive Summary")
    lines.append("")
    lines.append(executive_summary)
    lines.append("")

    if report_sections:
        for heading, key in [
            ("Key Developments", "key_developments"),
            ("Cross-Source Connections", "cross_source_connections"),
            ("Recommended Actions", "recommended_actions"),
            ("Signals to Monitor", "signals_to_monitor"),
        ]:
            items = report_sections.get(key, [])
            if items:
                lines.append(f"## {heading}")
                lines.append("")
                for item in items:
                    lines.append(f"- {item}")
                lines.append("")

    if core_ideas:
        lines.append("## Core Ideas")
        lines.append("")
        for idea in core_ideas:
            lines.append(f"- {idea}")
        lines.append("")

    if themes:
        lines.append("## Recurring Themes")
        lines.append("")
        for t in themes:
            lines.append(f"- {t}")
        lines.append("")

    if insights:
        lines.append("## Key Insights")
        lines.append("")
        for i, insight in enumerate(insights, 1):
            lines.append(f"{i}. {insight}")
        lines.append("")

    if contradictions:
        lines.append("## Contrarian / Surprising Points")
        lines.append("")
        for c in contradictions:
            lines.append(f"- {c}")
        lines.append("")

    if action_items:
        lines.append("## Actionable Takeaways")
        lines.append("")
        for a in action_items:
            lines.append(f"- [ ] {a}")
        lines.append("")

    if quotes:
        lines.append("## Key Quotes")
        lines.append("")
        for q in quotes:
            lines.append(f"> {q}")
        lines.append("")

    if opportunities:
        lines.append("## Opportunities")
        lines.append("")
        for o in opportunities:
            if isinstance(o, dict):
                text = o.get("opportunity", str(o))
                lines.append(f"- **{text}**")
                if o.get("why"):
                    lines.append(f"  - *Why:* {o['why']}")
            else:
                lines.append(f"- **{o}**")
        lines.append("")

    if why_it_matters:
        lines.append("## Why This Matters")
        lines.append("")
        for w in why_it_matters:
            lines.append(f"- {w}")
        lines.append("")

    if open_questions:
        lines.append("## Open Questions")
        lines.append("")
        for q in open_questions:
            lines.append(f"- {q}")
        lines.append("")

    if sources:
        lines.append("## Sources")
        lines.append("")
        for s in sources:
            if s:
                lines.append(f"- [{s['title']}]({s.get('url', '#')}) ({s['source_type']})")
        lines.append("")

    lines.append("---")
    lines.append(f"*Generated by SignalForge*")

    return "\n".join(lines)
