from datetime import datetime
from pathlib import Path

from weasyprint import HTML


TEMPLATE_PATH = Path(__file__).parent.parent.parent / "templates" / "report.html"


def generate_pdf(title: str, week_start: str, week_end: str,
                 executive_summary: str, source_count: int,
                 insights: list, action_items: list, quotes: list,
                 themes: list, opportunities: list, contradictions: list) -> bytes:
    template_path = TEMPLATE_PATH
    if not template_path.exists():
        return _generate_pdf_inline(title, week_start, week_end, executive_summary,
                                    source_count, insights, action_items, quotes,
                                    themes, opportunities, contradictions)

    html_content = template_path.read_text(encoding="utf-8")
    html = _render_html(html_content, title, week_start, week_end, executive_summary,
                        source_count, insights, action_items, quotes,
                        themes, opportunities, contradictions)
    return HTML(string=html).write_pdf()


def _generate_pdf_inline(title: str, week_start: str, week_end: str,
                         executive_summary: str, source_count: int,
                         insights: list, action_items: list, quotes: list,
                         themes: list, opportunities: list, contradictions: list) -> bytes:
    html = f"""<!DOCTYPE html>
<html>
<head><meta charset="utf-8">
<style>
  body {{ font-family: 'Georgia', serif; margin: 2.5cm; color: #1a1a1a; font-size: 11pt; line-height: 1.6; }}
  h1 {{ font-size: 20pt; border-bottom: 3px solid #2563eb; padding-bottom: 8px; color: #1e3a5f; }}
  h2 {{ font-size: 15pt; color: #2563eb; margin-top: 24px; }}
  .meta {{ color: #666; font-size: 10pt; margin-bottom: 20px; }}
  .summary {{ background: #f0f7ff; padding: 16px; border-left: 4px solid #2563eb; border-radius: 4px; }}
  .theme {{ display: inline-block; background: #e0e7ff; padding: 4px 10px; border-radius: 12px; font-size: 10pt; margin: 3px; }}
  blockquote {{ border-left: 3px solid #d1d5db; margin: 12px 0; padding: 8px 16px; color: #4b5563; font-style: italic; }}
  ul {{ padding-left: 20px; }}
  li {{ margin: 6px 0; }}
  footer {{ margin-top: 30px; padding-top: 10px; border-top: 1px solid #e5e7eb; color: #9ca3af; font-size: 9pt; }}
</style></head>
<body>
<h1>{title}</h1>
<div class="meta">
  <strong>Week:</strong> {week_start} to {week_end}<br>
  <strong>Sources:</strong> {source_count}<br>
  <strong>Generated:</strong> {datetime.now().strftime('%Y-%m-%d %H:%M')}
</div>

<h2>Executive Summary</h2>
<div class="summary">{executive_summary}</div>

{_section("Recurring Themes", _theme_list(themes))}
{_section("Key Insights", _insight_list(insights))}
{_section("Action Items", _action_list(action_items))}
{_section("Important Quotes", _quote_list(quotes))}
{_section("Opportunities", _opportunity_list(opportunities))}
{_section("Contradictions", _contradiction_list(contradictions))}

<footer>Generated by SignalForge</footer>
</body></html>"""
    return HTML(string=html).write_pdf()


def _section(title: str, content: str) -> str:
    if not content:
        return ""
    return f"<h2>{title}</h2>\n{content}\n"


def _theme_list(themes: list) -> str:
    if not themes:
        return ""
    items = "\n".join(f'  <span class="theme">{t}</span>' for t in themes)
    return f'<div class="themes">{items}</div>'


def _insight_list(insights: list) -> str:
    if not insights:
        return ""
    items = "\n".join(f"  <li>{i}</li>" for i in insights)
    return f"<ol>{items}</ol>"


def _action_list(actions: list) -> str:
    if not actions:
        return ""
    items = "\n".join(f"  <li><input type='checkbox' disabled> {a}</li>" for a in actions)
    return f"<ul>{items}</ul>"


def _quote_list(quotes: list) -> str:
    if not quotes:
        return ""
    items = "\n".join(f"  <blockquote>{q}</blockquote>" for q in quotes)
    return items


def _opportunity_list(opportunities: list) -> str:
    if not opportunities:
        return ""
    items = []
    for o in opportunities:
        if isinstance(o, dict):
            name = o.get("opportunity", str(o))
            why = o.get("why", "")
            items.append(f"  <li><strong>{name}</strong><br><em>{why}</em></li>")
        else:
            items.append(f"  <li>{o}</li>")
    return f"<ul>{''.join(items)}</ul>"


def _contradiction_list(contradictions: list) -> str:
    if not contradictions:
        return ""
    items = "\n".join(f"  <li>{c}</li>" for c in contradictions)
    return f"<ul>{items}</ul>"


def _render_html(template: str, **kwargs) -> str:
    return template.format(**kwargs)
