import os
import re
from datetime import datetime
from pathlib import Path
from fpdf import FPDF


def strip_markdown(text: str) -> str:
    text = re.sub(r'!\[([^\]]*)\]\([^)]+\)', r'\1', text)
    text = re.sub(r'\[([^\]]*)\]\([^)]+\)', r'\1', text)
    text = re.sub(r'^#{1,6}\s+', '', text, flags=re.MULTILINE)
    text = re.sub(r'[*_]{2}([^*_]+)[*_]{2}', r'\1', text)
    text = re.sub(r'[*_]([^*_]+)[*_](?!\*)', r'\1', text)
    text = re.sub(r'`{1,3}([^`]+)`{1,3}', r'\1', text)
    text = re.sub(r'^>\s?', '', text, flags=re.MULTILINE)
    text = re.sub(r'^[\s]*[-*+]\s+', '', text, flags=re.MULTILINE)
    text = re.sub(r'^\s*\d+[.)]\s+', '', text, flags=re.MULTILINE)
    text = re.sub(r'^-{3,}\s*$', '', text, flags=re.MULTILINE)
    text = re.sub(r'\n{3,}', '\n\n', text)
    return text.strip()

FONT_DIR = Path(os.environ.get("WINDIR", "C:\\Windows")) / "Fonts"

_FONTS = {
    "georgia": {
        "regular": str(FONT_DIR / "georgia.ttf"),
        "bold": str(FONT_DIR / "georgiab.ttf"),
        "italic": str(FONT_DIR / "georgiai.ttf"),
        "bold_italic": str(FONT_DIR / "georgiaz.ttf"),
    },
    "constantia": {
        "regular": str(FONT_DIR / "constan.ttf"),
        "bold": str(FONT_DIR / "constanb.ttf"),
        "italic": str(FONT_DIR / "constani.ttf"),
        "bold_italic": str(FONT_DIR / "constanz.ttf"),
    },
    "cambria": {
        "regular": str(FONT_DIR / "cambria.ttc"),
        "bold": str(FONT_DIR / "cambriab.ttf"),
        "italic": str(FONT_DIR / "cambriai.ttf"),
        "bold_italic": str(FONT_DIR / "cambriaz.ttf"),
    },
    "calibri": {
        "regular": str(FONT_DIR / "calibri.ttf"),
        "bold": str(FONT_DIR / "calibrib.ttf"),
        "italic": str(FONT_DIR / "calibrii.ttf"),
        "bold_italic": str(FONT_DIR / "calibriz.ttf"),
    },
    "segoe": {
        "regular": str(FONT_DIR / "segoeui.ttf"),
        "bold": str(FONT_DIR / "segoeuib.ttf"),
        "italic": str(FONT_DIR / "segoeuii.ttf"),
        "bold_italic": str(FONT_DIR / "segoeuiz.ttf"),
    },
    "arial": {
        "regular": str(FONT_DIR / "arial.ttf"),
        "bold": str(FONT_DIR / "arialbd.ttf"),
        "italic": str(FONT_DIR / "ariali.ttf"),
        "bold_italic": str(FONT_DIR / "arialbi.ttf"),
    },
}

LMARGIN = 15
RMARGIN = 15
EFFECTIVE_W = 210 - LMARGIN - RMARGIN  # 180mm for A4
INDENT = 6


def _find_unicode_font() -> str:
    for name, paths in _FONTS.items():
        if os.path.exists(paths["regular"]):
            return name
    raise RuntimeError("No Unicode font found. Install Georgia, Constantia, Cambria, Calibri, Segoe UI, or Arial.")


class ReportPDF(FPDF):
    def __init__(self):
        super().__init__()
        self._font = _find_unicode_font()
        paths = _FONTS[self._font]
        self.add_font("Uni", "", paths["regular"], uni=True)
        self.add_font("Uni", "B", paths["bold"], uni=True)
        self.add_font("Uni", "I", paths["italic"], uni=True)
        self.add_font("Uni", "BI", paths["bold_italic"], uni=True)
        self.set_left_margin(LMARGIN)
        self.set_right_margin(RMARGIN)
        self.set_auto_page_break(auto=True, margin=25)

    def header(self):
        if self.page_no() == 1:
            return
        self.set_font("Uni", "B", 10)
        self.set_text_color(30, 58, 95)
        self.cell(0, 8, "SignalForge Weekly Report", align="L")
        self.set_font("Uni", "I", 8)
        self.set_text_color(156, 163, 175)
        self.cell(0, 8, f"Page {self.page_no()}", align="R", new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(200, 200, 200)
        self.line(LMARGIN, self.get_y(), 210 - RMARGIN, self.get_y())
        self.ln(4)

    def footer(self):
        self.set_y(-18)
        self.set_font("Uni", "I", 8)
        self.set_text_color(156, 163, 175)
        self.cell(0, 10, f"Generated by SignalForge  |  Page {self.page_no()}/{{nb}}", align="C")

    def section_title(self, title: str):
        self.ln(3)
        self.set_font("Uni", "B", 13)
        self.set_text_color(37, 99, 235)
        self.cell(0, 8, title, new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(37, 99, 235)
        self.line(LMARGIN, self.get_y(), LMARGIN + 30, self.get_y())
        self.ln(4)

    LH = 6.5

    def body_text(self, text: str):
        self.set_font("Uni", "", 10.5)
        self.set_text_color(26, 26, 26)
        self.multi_cell(0, self.LH, text)
        self.ln(2)

    def _bullet_item(self, text: str, marker: str = "-"):
        self.set_font("Uni", "", 10.5)
        self.set_text_color(26, 26, 26)
        self.cell(INDENT)
        self.cell(5, self.LH, marker)
        w = EFFECTIVE_W - INDENT - 5
        self.multi_cell(w, self.LH, text)
        self.ln(1)

    def _number_item(self, num: int, text: str):
        self.set_font("Uni", "", 10.5)
        self.set_text_color(26, 26, 26)
        self.cell(INDENT)
        self.cell(5, self.LH, f"{num}.")
        w = EFFECTIVE_W - INDENT - 5
        self.multi_cell(w, self.LH, text)
        self.ln(1)

    def bullet_list(self, items: list):
        for item in items:
            if isinstance(item, dict):
                self._bullet_item(item.get("opportunity", str(item)), "-")
                if item.get("why"):
                    self._bullet_item(f"Why: {item['why']}", "  ")
            else:
                self._bullet_item(str(item))
        self.ln(2)

    def numbered_list(self, items: list):
        for i, item in enumerate(items, 1):
            self._number_item(i, str(item))
        self.ln(2)

    def quote_list(self, quotes: list):
        for q in quotes:
            self.set_fill_color(249, 250, 251)
            self.set_font("Uni", "I", 10.5)
            self.set_text_color(75, 85, 99)
            self.cell(INDENT)
            self.multi_cell(EFFECTIVE_W - INDENT, self.LH, f'"{q}"', fill=True)
            self.ln(2)

    def meta_line(self, label: str, value: str):
        self.set_font("Uni", "B", 10.5)
        self.set_text_color(80, 80, 80)
        self.cell(20, 6, label)
        self.set_font("Uni", "", 10.5)
        self.set_text_color(26, 26, 26)
        self.cell(0, 6, value, new_x="LMARGIN", new_y="NEXT")

    def theme_tags(self, themes: list):
        x_start = LMARGIN + INDENT
        self.set_x(x_start)
        self.set_font("Uni", "B", 10)
        for i, t in enumerate(themes):
            label = f"  {t}  "
            tw = self.get_string_width(label) + 2
            if self.get_x() + tw > 210 - RMARGIN:
                self.ln(6)
                self.set_x(x_start)
            self.set_fill_color(224, 231, 255)
            self.set_text_color(30, 58, 95)
            self.cell(tw, 6, label, fill=True)
            self.cell(2)
        self.ln(8)

    def summary_block(self, text: str):
        self.set_fill_color(240, 247, 255)
        self.set_draw_color(37, 99, 235)
        self.set_font("Uni", "", 10.5)
        self.set_text_color(26, 26, 26)
        self.multi_cell(0, self.LH, text, fill=True)
        self.ln(2)

    def cover_page(self, title: str, week_start: str, week_end: str,
                   source_count: int):
        self.add_page()
        self.ln(30)
        self.set_font("Uni", "B", 24)
        self.set_text_color(30, 58, 95)
        self.multi_cell(0, 10, title, align="C")
        self.ln(6)
        self.set_draw_color(37, 99, 235)
        self.set_line_width(0.5)
        cx = 210 / 2
        self.line(cx - 25, self.get_y(), cx + 25, self.get_y())
        self.set_line_width(0.2)
        self.ln(10)
        self.set_font("Uni", "", 12)
        self.set_text_color(80, 80, 80)
        self.cell(0, 8, f"{week_start}  to  {week_end}", align="C", new_x="LMARGIN", new_y="NEXT")
        self.ln(4)
        self.set_font("Uni", "B", 14)
        self.set_text_color(37, 99, 235)
        self.cell(0, 8, f"{source_count} source{'s' if source_count != 1 else ''}", align="C", new_x="LMARGIN", new_y="NEXT")
        self.ln(8)
        self.set_font("Uni", "", 10.5)
        self.set_text_color(156, 163, 175)
        self.cell(0, 6, f"Generated {datetime.now().strftime('%B %d, %Y at %H:%M')}", align="C", new_x="LMARGIN", new_y="NEXT")
        self.set_font("Uni", "I", 9)
        self.cell(0, 6, "SignalForge — Local-first AI Knowledge Digest", align="C", new_x="LMARGIN", new_y="NEXT")


def generate_pdf(title: str, week_start: str, week_end: str,
                 executive_summary: str, source_count: int,
                 insights: list, action_items: list, quotes: list,
                 themes: list, opportunities: list, contradictions: list,
                 report_sections: dict | None = None) -> bytes:
    pdf = ReportPDF()
    pdf.alias_nb_pages()

    pdf.cover_page(title, week_start, week_end, source_count)

    pdf.add_page()
    pdf.section_title("Executive Summary")
    clean = strip_markdown(executive_summary)
    pdf.summary_block(clean)

    if report_sections:
        for heading, key in [
            ("Key Developments", "key_developments"),
            ("Cross-Source Connections", "cross_source_connections"),
            ("Recommended Actions", "recommended_actions"),
            ("Signals to Monitor", "signals_to_monitor"),
        ]:
            items = report_sections.get(key, [])
            if items:
                pdf.section_title(heading)
                pdf.bullet_list(items)

    if themes:
        pdf.section_title("Recurring Themes")
        pdf.theme_tags(themes)

    if insights:
        pdf.section_title("Key Insights")
        pdf.numbered_list(insights)

    if action_items:
        pdf.section_title("Action Items")
        pdf.bullet_list(action_items)

    if quotes:
        pdf.section_title("Important Quotes")
        pdf.quote_list(quotes)

    if opportunities:
        pdf.section_title("Opportunities")
        pdf.bullet_list(opportunities)

    if contradictions:
        pdf.section_title("Contradictions")
        pdf.bullet_list(contradictions)

    return pdf.output()
